getgenv().Settings = {
    Mailing = {
        ["Basic Coin Jar"] = {Class = "Misc", Amount = 200},
        ["Mini Lucky Block"] = {Class = "Misc", Amount = 100},
        ["Comet"] = {Class = "Misc", Amount = 200},
        ["Coins 7 "] = {Class = "Potion", Amount = 10},
        ["Damage 7"] = {Class = "Potion", Amount = 10},
        ["Banana"] = {Class = "Fruit", Amount = 100},
        ["Apple"] = {Class = "Fruit", Amount = 100},
        ["Orange"] = {Class = "Fruit", Amount = 100},
        ["Pineapple"] = {Class = "Fruit", Amount = 100},
        ["Watermelon"] = {Class = "Fruit", Amount = 100},
        ["Coins 7"] = {Class = "Enchant", Amount = 2},
        ["Tap Power 7"] = {Class = "Enchant", Amount = 1},
        ["Criticals 7"] = {Class = "Enchant", Amount = 1},
        ["Strong Pets 7"] = {Class = "Enchant", Amount = 1},
        ["Diamonds"] = {Class = "Currency", Amount = 10000},
    },
    Users = {
        "sincereFlamingo159",
        "resolvedJerky519",
        "ferventSardines455",
        "fondBoars253",
        "jumpyBuzzard471",
        "kindOil380",
        "awedLeopard885",
        "anxiousLemur686",
        "wakefulPorpoise086",
        "importedBuzzard220",
        "curiousThrush025",
        "wrathfulApricots749",
        "yearningLard838",
        "affectedCamel964",
        "puzzledPie483",
        "giddyApples322",
        "resolvedPlover326",
        "gutturalPudding565",
        "soreFlamingo531",
        "grumpyBoars450",
        "cynicalGatorade415",
        "resolvedBittern480",
        "dreadfulIcecream119",
        "unhappyCardinal392",
        "spiritedPlover045",
        "holisticRuffs741",
        "kindCake335",
        "amazedPretzels083",
        "kindSnail450",
        "resolvedTruffle250",
        "adoringDove231",
        "cheerfulTeal086",
        "pacifiedLapwing770",
        "similarChough237",
        "alertBobolink248",
        "enragedEggs590",
        "importedCur228",
        "dopeyChowder123",
        "insecureMandrill091",
        "betrayedThrushe768",
    },
    ["Split Items Evenly"] = false, --// False -> it will send the Amount per account.
    ["Only Online Accounts"] = false,
    ["Developer Mode"] = false,

    [[ Thank you for using System Exodus <3! ]]
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/86847850c3165379f5be2d9d071eaccb.lua"))()
