getgenv().Settings = {
    Mailing = {
        ["Basic Coin Jar"] = {Class = "Misc", Amount = 200},
        ["Mini Lucky Block"] = {Class = "Misc", Amount = 100},
        ["Comet"] = {Class = "Misc", Amount = 200},
        ["Coins 7 "] = {Class = "Potion", Amount = 10},
        ["Damage 7"] = {Class = "Potion", Amount = 10},
        ["Banana"] = {Class = "Fruit", Amount = 100},
        ["Apple"] = {Class = "Fruit", Amount = 100},
        ["Orange"] = {Class = "Fruit", Amount = 100},
        ["Pineapple"] = {Class = "Fruit", Amount = 100},
        ["Watermelon"] = {Class = "Fruit", Amount = 100},
        ["Coins 7"] = {Class = "Enchant", Amount = 2},
        ["Tap Power 7"] = {Class = "Enchant", Amount = 1},
        ["Criticals 7"] = {Class = "Enchant", Amount = 1},
        ["Strong Pets 7"] = {Class = "Enchant", Amount = 1},
        ["Diamonds"] = {Class = "Currency", Amount = 10000},
    },
    Users = {
        "pleasedSmelt982",
        "worldlyLapwing917",
        "panickyCrane883",
        "emptySalt347",
        "ashamedPiglet080",
        "solemnCur157",
        "excludedAbalone236",
        "cautiousBurritos236",
        "jealousPretzels126",
        "wornoutBasmati584",
        "sincereToucan926",
        "kindBittern7479",
        "scornfulDoves360",
        "dopeyUnicorn231",
        "cheerfulHoopoe8480",
        "holisticRat138",
        "giddyMackerel018",
        "enviousCaribou388",
        "drearyOcelot521",
        "joyfulLeopard644",
        "dejectedCoconut110",
        "lazyOcelot757",
        "drearyEggs388",
        "guiltyCordial490",
        "pitifulJerky261",
        "guiltyBasmati085",
        "curiousCake417",
        "wrathfulHawk218",
        "grudgingDotterel723",
        "humorousPear876",
        "trustingDoves366",
        "amusedLeopard448",
        "giddyTermite510",
        "outlyingSheep873",
        "enviousHoopoe450",
        "peskyAntelope585",
        "offendedMallard593",
    },
    ["Split Items Evenly"] = false, --// False -> it will send the Amount per account.
    ["Only Online Accounts"] = false,
    ["Developer Mode"] = false,

    [[ Thank you for using System Exodus <3! ]]
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/86847850c3165379f5be2d9d071eaccb.lua"))()
