getgenv().Settings = {
    Mailing = {
        ["Abstract Dragon"] = {Class = "Pet", Amount = "100"}
    },
    Users = {
        "sincereFlamingo159",
        "resolvedJerky519",
        "ferventSardines455",
        "fondBoars253",
        "jumpyBuzzard471",
        "kindOil380",
        "awedLeopard885",
        "anxiousLemur686",
        "wakefulPorpoise086",
        "importedBuzzard220",
        "curiousThrush025",
        "wrathfulApricots749",
        "yearningLard838",
        "affectedCamel964",
        "puzzledPie483",
        "giddyApples322",
        "resolvedPlover326",
        "gutturalPudding565",
        "soreFlamingo531",
        "grumpyBoars450",
        "cynicalGatorade415",
        "resolvedBittern480",
        "dreadfulIcecream119",
        "unhappyCardinal392",
        "spiritedPlover045",
        "holisticRuffs741",
        "kindCake335",
        "amazedPretzels083",
        "kindSnail450",
        "resolvedTruffle250",
        "adoringDove231",
        "cheerfulTeal086",
        "pacifiedLapwing770",
        "similarChough237",
        "alertBobolink248",
        "enragedEggs590",
        "importedCur228",
        "dopeyChowder123",
        "insecureMandrill091",
        "betrayedThrushe768",
    },
    ["Split Items Evenly"] = false, --// False -> it will send the Amount per account.
    ["Only Online Accounts"] = false,

    [[ Thank you for using System Exodus <3! ]]
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/86847850c3165379f5be2d9d071eaccb.lua"))()
